// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITOw9xsCu9VpkfrNFsy85RU_jbKmu43U',
    appId: '1:452845677908:web:ba2e98b83725e47b736cc1',
    messagingSenderId: '452845677908',
    projectId: 'psmmanagementsystem',
    authDomain: 'psmmanagementsystem.firebaseapp.com',
    storageBucket: 'psmmanagementsystem.firebasestorage.app',
    measurementId: 'G-HHWJLH5MDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11ZjVTVJjRVVppyCqV5gtF_B8PKnVj5w',
    appId: '1:452845677908:android:d77c5bdf0dbdcb13736cc1',
    messagingSenderId: '452845677908',
    projectId: 'psmmanagementsystem',
    storageBucket: 'psmmanagementsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3DxpZn4PcTwjSuffoSVsKfpmboujeP4',
    appId: '1:452845677908:ios:3028b07615560570736cc1',
    messagingSenderId: '452845677908',
    projectId: 'psmmanagementsystem',
    storageBucket: 'psmmanagementsystem.firebasestorage.app',
    iosBundleId: 'com.example.psmms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3DxpZn4PcTwjSuffoSVsKfpmboujeP4',
    appId: '1:452845677908:ios:3028b07615560570736cc1',
    messagingSenderId: '452845677908',
    projectId: 'psmmanagementsystem',
    storageBucket: 'psmmanagementsystem.firebasestorage.app',
    iosBundleId: 'com.example.psmms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITOw9xsCu9VpkfrNFsy85RU_jbKmu43U',
    appId: '1:452845677908:web:c98a2dde731bfc73736cc1',
    messagingSenderId: '452845677908',
    projectId: 'psmmanagementsystem',
    authDomain: 'psmmanagementsystem.firebaseapp.com',
    storageBucket: 'psmmanagementsystem.firebasestorage.app',
    measurementId: 'G-J2K9L9R7XP',
  );

}